### ISSUE TITLE
ejectuable en vez de ejecutable

### ISSUE THREAD

**Issue by zifrara** [ousia/aprender-context#1]
página 60: una distribución portátil
ConTEXt no es propiamente un archivo ejectuable que acceda a
otros archivos llamados bibliotecas 49
. En la práctica, el núcleo es un
conjunto de más de tres mil setecientos archivos. Sólo el núcleo no
funcionaría,

**Comment by ousia** [comment]
Muchas gracias por la errata, @zifrara.

Ya está corregido. Espero poder tener una versión nueva (con más texto) en breve.
