### ISSUE TITLE
ERRATA: «muchas veces es que sus límites»

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#10]
Corrección: «muchas veces es porque sus límites».

**Comment by ousia** [comment]
Muchas gracias, @NikaZhenya.

He preferido evitar el «es» y lo he sustituido por «significa que», quedando el resultado:

> Que algunas personas tengan mayor manejo informático, muchas veces significa que sus límites están más avanzados que los del resto.

**Comment by ousia** [comment]
Añado «sólo»:

> Que algunas personas tengan mayor manejo informático, muchas veces sólo significa que sus límites están más avanzados que los del resto.
