### ISSUE TITLE
ERRATA: «Nadie tiene que sufrir que aprendamos»

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#11]
Corrección: «Nadie tiene que sufrir para que aprendamos».

**Comment by ousia** [comment]
@NikaZhenya, muchas gracias.

No sé si veo la errata o el error.

No es «para que». En todo caso, sería «porque».

No sé si así te sonaría más claro:

> Nadie tiene que sufrir [el hecho de] que estemos aprendiendo...

El texto entre corchetes es explicativo, nada más. ¿Sería más claro así?

**Comment by ousia** [comment]
De hecho, he decidido:

> Nadie tiene que sufrir porque estemos aprendiendo ConTeXt.

Cierro la incidencia. Si no fuese claro todavía, agradecería el comentario.
