### ISSUE TITLE
ALTERNATIVA: mayor automatización de la etiqueta \footnote{}

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#19]
He preferido la aproximación de tener un documento distinto con las notas al pie de los textos principales y de ahí empatarlos para que se añadan automáticamente. Ya di el enlace al script en #18  pero lo repito: https://github.com/NikaZhenya/Pecas/tree/master/EPUB/3-Notas

**Comment by ousia** [comment]
No entiendo muy bien a dónde apuntas.

Si no te parece mal, cierro esta incidencia y seguimos en la #18.
