### ISSUE TITLE
ERRATA: «fácil que agobiase»

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#2]
Corrección: «fácil agobiarse».

**Comment by ousia** [comment]
Muchas gracias, @NikaZhenya.

Lo siento, pero creo que no hay errata:

> No pretendo hacer un análisis completo, porque es fácil que agobiase.

Es «fácil que agobiase» el análisis. Un infinitivo como pasiva refleja (si recuerdo bien cómo se llamaban estas cosas 😉) creo que es más rebuscado.

Pero mi construcción estaba mal. Creo que ahora la frase está mejor:

> No pretendo hacer un análisis completo, porque sería fácil que nos agobiase.
