### ISSUE TITLE
COMENTARIO: sobre la introducción

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#22]
Primero que nada: creo que tuve que haber aglutinado los *issues* para evitar que se generaran tantos jajajaj, ¿cómo lo prefieres?

Me gusta la intención del libro y la introducción no estuvo nada mal pero pese a que indicas que será extensa, pienso que podría sintetizarse un poco más. Pienso que a lo largo de esta sección reiteras mucho en:

* Si se quiere algo fácil, ConTeXt no es el libro.
* La diferencia de ConTeXt con los procesadores de texto.
* La pertinencia de ConTeXt frente a otros sistemas de publicación digital.

Es importante abordarlos, pero quizá sea mejor tratarlos en una subsección para evitar repeticiones a lo largo de la introducción. Como sea, es una sugerencia xD

Respecto a la explicación sobre las ediciones (PDF y EPUB) y los agradecimientos, los pondría antes de la introducción y no como una parte al final de la introducción. Creo que es más claro porque esos dos apartados no tienen que ver sobre ConTeXt en sí y la intención introductoria de esta obra, sino más sobre cuestiones que son ajenas al discurso principal del libro.

Pero bueno, te seguiré molestando en los próximos capítulos!

**Comment by ousia** [comment]
Hola @NikaZhenya,

muchas gracias por tus comentarios. Perdona que no pueda contestarte hoy a todo, pero por lo menos espero poder contestar a esta entrada.

Por cierto, entiendo que eres el autor de [esta entrada de bitácora](http://marianaeguaras.com/adobe-el-omnipresente/).

> Primero que nada: creo que tuve que haber aglutinado los issues para evitar que se generaran tantos jajajaj, ¿cómo lo prefieres?

Mejor una incidencia por problema individual.

> Me gusta la intención del libro y la introducción no estuvo nada mal pero pese a que indicas que será extensa, pienso que podría sintetizarse un poco más.

Muchas gracias por la crítica. Permíteme disentir.

Sin que no pueda dirigirse a otras personas, el libro no está pensado para alguien que haya manejado TeX antes.

Por eso, me temo que hay que repetir mucho cosas que quizá sean obvias para otras personas.

> Pienso que a lo largo de esta sección reiteras mucho en:
>
> * Si se quiere algo fácil, ConTeXt no es el libro.
> * La diferencia de ConTeXt con los procesadores de texto.
> * La pertinencia de ConTeXt frente a otros sistemas de publicación digital.

No formularía exactamente así los puntos básicos, pero supongo que es una manera de expresarlo.

Ahora bien, hay un cuarto punto en el que se ve que no he insistido suficiente: la única manera de aprender ConTeXt es teclear código y ver qué pasa.

> Respecto a la explicación sobre las ediciones (PDF y EPUB) y los agradecimientos, los pondría antes de la introducción y no como una parte al final de la introducción.

Es lógico y perfectamente legítimo que veamos las cosas de diferente manera.

Creo que el lugar de ese capitulo está bien donde está, dentro de la parte introductoria.

O entiendo que antes de la introducción está un prólogo, y no es materia _claramente_ de un prólogo o prefacio.

> Pero bueno, te seguiré molestando en los próximos capítulos!

Sinceramente, te estoy muy agradecido. En absoluto es una molestia, sino una gran ayuda.

**Comment by perrotuerto** [comment]
Gracias por la respuesta, como son sugerencias na más, pos que se apliquen las que se consideren convenientes :D

Solo indicar que quizá no tanto como crear un prólogo o un prefacio, sino tal vez un «Notas para esta edición» o algo semejante al inicio para colocar ahí los agradecimientos y lo relativo a la edición?

Sí, escribo unas entradas para el blog de Mariana Eguaras: https://github.com/NikaZhenya/entradas-eguaras

Saludos!

**Comment by ousia** [comment]
@NikaZhenya, sntiendo que puedo cerrar esta incidencia.

Si no es así (como con cualquier otra), me lo dices, la vuelvo a abrir y seguimos «discutiendo».
