### ISSUE TITLE
¿editor para principiantes?

### ISSUE THREAD

**Issue by ousia** [ousia/aprender-context#23]
@NikaZhenya,

permíteme una pregunta: ¿qué editor de texto multiplataforma usarías para principiantes?

Me gustaría saber porque me doy cuenta que debo explicar la configuración completa de un editor para usarlo con ConTeXt.

El editor perfecto (no es que me apasione, yo no lo uso) me parece que es _TeXworks_. Pero curiosamente no permite en _Unix_ una orden tal que:

```
source ~/context/tex/setuptex && contextjit $fullname
```

La carga de las rutas es necesaria, porque _ConTeXt Suite_ es una distribución portátil. Así es mucho más ligera. En _Windows_, tampoco permitirá la orden adaptada.

¿Se te ocurre algún editor sencillo? Sencillo para principiantes, no para quienes tienen costumbre de escribir código (del tipo que sea).

La particularidad es que tiene que funcionar para _Windows_, _MacOS X_ y _Linux_. Si no es de programación libre o abierta, que al menos sea gratuito.

**Comment by perrotuerto** [comment]
Precisamente por la particularidad que mencionas al final yo usaba TeXworks, pero también por las limitantes que indicas ahora estoy con TeXstudio. De ahí en más no utilizado otros entornos para TeX, sino editores de texto plano o de código + terminal :/

**Comment by perrotuerto** [comment]
No freeware, open o free software! jajaja

**Comment by ousia** [comment]
Muchas gracias por tu ayuda, @NikaZhenya.

Me temo que _TeXstudio_ no me sirve. Está bien siempre que vayas a usar LaTeX y que tengas experiencia.

Si no se da eso, la mayoría del interfaz visual aturde. Y para quien use ConTeXt, independientemente de los conocimientos que tenga, no le sirve absolutamente de nada.

De veras te lo agradezco. Si me permites unos pensamientos (o rebuznos, no sé 😜) en voz alta, suelto aquí algunos:

* ¿Por qué hablamos de TeX cuando queremos decir LaTeX?

    En el caso que nos ocupa, _TeXstudio_ y _TexitEasy_ están desarrollados únicamente para LaTeX. No hay nada de malo en eso. Pero creo que es más congruente un nombre como _LaTeXila_.

    La única excepción es _TeXworks_, que al menos se da cuenta de que ConTeXt es una opción viable.

Los dos exabruptos siguientes tienen que ver con las condiciones previas de por qué TeX (sí, TeX, el lenguaje de composición tipográfica y el compilador) no tiene más audiencia.

* El editor no es ninguna tontería o algo secundario para quien empieza o quiere ver cómo va eso. Y eso lo es en dos sentidos:

    * Visualmente, no debe haber más que espacio para escribir y para poder ver el resultado. La ventana de órdenes sólo debe mostrarse en caso de error. Lo demás sólo confunde.

    * Funcionalmente, tiene que ser pulsar una tecla para compilar y visualizar el documento final.

    Por supuesto, podemos complicar eso, pero sólo conseguiremos hacer más difícil empezar a aprender a usar TeX.

    No es serio que la expectativa de uso sea gente que tiene experiencia con código. Por eso, no valen los editores de código generales. Usar TeX no debería ser aprender programación (ni siquiera tipográfica). Es sólo escribir texto que contiene órdenes.

    De lo que recuerdo de su uso, LaTeX es especialmente malo en este punto. Hace como una década que dejé de usarlo y espero que haya mejorado. En su momento no había una orden para ejecutar todas las pasadas, ni para hacer índices o la bibliografía. No es una compilación eficiente. 

* ¿Cuándo abandonaremos la maldita jerga? Es posible que se note más en español, pero pasa en inglés también.

    Si hablamos una jerga que nadie entiende, podremos fundar una secta, pero así sólo podremos ganar adeptos.

    En todos los ámbitos del saber existe terminología y jerga. Usar barbarismos y tecnicismos puede ser la mejor manera de que no quien escuche no llegue a entender nada. Porque realmente no se está explicando nada, quien habla se cuenta el cuento a sí mismo.

    _Free software_ podría ser un ejemplo entre millones. Pero pasa en otros ámbitos. El maldito _a priori_ y _a posteriori_ cuando se usa temporalmente. Si nos gustan los latinismos, serían _ex ante_ y _ex post_. Muchas veces, es incluso «antes» y «después». O «con anterioridad» y «con posterioridad». En _a priori_ y _a posteriori_ no se habla de sucesión temporal. Es desarrollo lógico u ontológico.

    El problema de la jerga es que nos impide pensar y nos dificulta entender y hacer entender. Mientras no nos liberemos de ella, predicaremos. Y no es que me horrorice hacerlo, es que necesito explicar.

En fin, aquí quedan los exabruptos. No tienen que ver contigo, sólo me has brindado la ocasión. Pero cada vez más, creo que tenemos que comenzar a pensar y dejar de repetir argumentaciones.

**Comment by ousia** [comment]
@NikaZhenya, ya he descubierto cómo se configura _TeXworks_ con la _ConTeXt Suite_. Lo explicaré en parte del capítulo 4.

Cierro la incidencia. Pero podemos seguir comentando.
