### ISSUE TITLE
SUGERENCIA: menos itálicas

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#5]
Las palabras:

* InDesign
* Adobe
* Linux
* Windows
* MacOS X
* Assimil
* TeX Gyre Pagella
* GFD Didot
* Cousine
* Amazon
* Adobe Reader Mobile
* Sony Reader PRS-T1
* Sony

No necesitan ir en itálicas. Véase: http://www.fundeu.es/wp-content/uploads/2013/05/CursivasGuiaFundeu.pdf

**Comment by ousia** [comment]
Perdóname el cansancio, porque la respuesta será directa.

Creo que la Fundéu no es clara (en nombres de objetos singulares, creo que rizan el rizo).

Los títulos de obras intelectuales van en cursiva, Los nombres de persona no van en cursiva, aunque ambos empiecen por mayúscula.

Los programas informáticos y tipografías son obras intelectuales.

Las marcas comerciales son creaciones intelectuales. Por eso, especialmente las que usan denominaciones extranjeras, deben ir en cursiva.

**Comment by perrotuerto** [comment]
Fundéu se basa principalmente en la *Ortografía* del 2010. La puse como fuente porque la *Ortografía* no la encontré en línea. Mi base es esa obra. Te recomiendo que leas el punto 4.2.4.11.4 donde habla de las marcas comerciales, programas infórmaticos, y demás cuestiones relacionadas a «lo digital». Explícitamente indica que **son nombres propios y deben escribirse** como tales. No son considerados como *obras intelectuales*. Pero da igual, con que haya uniformidad!

**Comment by ousia** [comment]
Que un programa informático es una obra intelectual lo indica hasta el derecho: se protege bajo derechos de autor.

No tengo acceso a la la _Ortografía_ de la RAE, pero no entiendo por qué he de escribir _Kritik der reinen Vernunft_ (la _Crítiica de la razón pura_ kantiana) tanto en español como en alemán, pero _Adobe Indesign_ puede llegar a ser el nombre de mi vecino sueco, si no lo pongo en cursiva.

Por supuesto agradezco tu insistencia, pero la falta de criterio académico (o lo que así percibo), a veces me sorprende mucho.

Disiento de las autoridades (seré muy rebelde, pero argumentando por qué).

Creo que una marca comercial extranjera (la _Deutsche Bahn_ [literalmente, los ferrocarriles alemanes]) no es lo mismo que un nombre extranjero (se me viene a la cabeza Karl Ove Knausgård).

En general, creo que es importante para no confudir lo que son personas (seres vivos) con lo que no lo son.
