### ISSUE TITLE
DUDA: redacción poco clara

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#6]
No entendí a lo que te refieres con «Esto supone un texto con dos cuerpos de notas [...] resultado final». ¿Podrías explicarme?

**Comment by ousia** [comment]
Pues en vez de poner un sólo cuerpo de notas (las variantes textuales) y luego añadir en los márgenes las referencias a otros textos, ponerlos en dos cuerpos de notas.

Un ejemplo de lo primero es:

![john-253](https://user-images.githubusercontent.com/203767/29243532-63171002-7fa1-11e7-9d40-fbbc1d13a7aa.png)

Un ejemplo de lo segundo sería:

![hefes-1](https://user-images.githubusercontent.com/203767/29243471-1bddf83c-7fa0-11e7-8749-088a8bcc79f9.png)

Siento que ambos textos estén en griego. Pero tienen que ser antiguos.

**Comment by ousia** [comment]
Entiendo que está aclarado, al menos con la segunda imagen.
