### ISSUE TITLE
ERRATA: «Le ponermos a trabajar»

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#7]
Corrección: «Lo ponemos a trabajar».

**Comment by ousia** [comment]
Corrijo por «le ponemos a trabajar». En España, al menos, se admite «le» por «lo» (no por «la») sin que sea considerado leísmo.

**Comment by ousia** [comment]
Aunque es cierto que sólo se permite para personas en masculino.

En este caso, estoy usando como persona masculina (mi asistente tipográfico).

Lo siento, pero «lo ponemos a hacer» me suena a laísmo.
