### ISSUE TITLE
DUDA: ¿redacción rara?

### ISSUE THREAD

**Issue by perrotuerto** [ousia/aprender-context#8]
No entendí la expresión «ahí te las compongas»...

**Comment by ousia** [comment]
Debe ser un españolismo, pero lo dejaré porque creo que es especialmente afortunado.

Quiere decir que lo tienes que arreglar tú solo. En este caso, ConTeXt lo tiene que arreglar sólo ([_Diccionario de la lengua española_](http://dle.rae.es/?id=A28RNZ3#Ez2ICjj)).

**Comment by ousia** [comment]
He puesto una nota explicativa.
